name: ci
on:
  push:
  workflow_dispatch:
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2020-09-05T23%3A57%3A59.585000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install
      - run: npm test
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2020-09-05T23%3A57%3A59.585000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2020-09-05T23%3A57%3A59.585000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test
      - run: npm run coverage
  esm:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2020-09-05T23%3A57%3A59.585000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run test:esm
  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2020-09-05T23%3A57%3A59.585000Z@time-machines-npm.sealsecurity.io/
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: npm install
      - run: npm run compile
      - uses: denoland/setup-deno@v2
      - run: |
          deno --version
          deno test --allow-read test/deno/y18n-test.ts
